#!/bin/bash

# 🔐 Configuration des secrets Netlify pour déploiement automatique
# Script de configuration GitHub Actions + Netlify

echo "🔐 CONFIGURATION AUTOMATISATION NETLIFY"
echo "════════════════════════════════════════════"

echo ""
echo "📋 ÉTAPES REQUISES POUR ACTIVER LE DÉPLOIEMENT AUTOMATIQUE :"
echo ""

echo "1️⃣ OBTENIR LES TOKENS NETLIFY :"
echo "   • Connectez-vous sur https://app.netlify.com"
echo "   • Allez dans 'User settings' → 'Applications' → 'Personal access tokens'"
echo "   • Créez un nouveau token avec les permissions 'sites:write'"
echo "   • Copiez le token généré (NETLIFY_AUTH_TOKEN)"
echo ""

echo "2️⃣ OBTENIR L'ID DU SITE NETLIFY :"
echo "   • Dans votre dashboard Netlify, sélectionnez votre site"
echo "   • Allez dans 'Site settings' → 'General' → 'Site details'"
echo "   • Copiez l'API ID du site (NETLIFY_SITE_ID)"
echo ""

echo "3️⃣ CONFIGURER LES SECRETS GITHUB :"
echo "   • Allez sur https://github.com/htconfort/facturation-MYconfortdu-20-07-2025"
echo "   • Cliquez sur 'Settings' → 'Secrets and variables' → 'Actions'"
echo "   • Ajoutez ces 2 secrets :"
echo ""
echo "   📝 Nom: NETLIFY_AUTH_TOKEN"
echo "   🔑 Valeur: [Votre token personnel Netlify]"
echo ""
echo "   📝 Nom: NETLIFY_SITE_ID"
echo "   🔑 Valeur: [L'API ID de votre site Netlify]"
echo ""

echo "4️⃣ CRÉER LE SITE NETLIFY (si pas encore fait) :"
echo "   • Sur Netlify, cliquez 'Add new site' → 'Import an existing project'"
echo "   • Connectez GitHub et sélectionnez le repository"
echo "   • Configuration de build :"
echo "     - Build command: npm run build"
echo "     - Publish directory: dist"
echo "     - Site name: myconfort-facturation (ou autre)"
echo ""

echo "5️⃣ VÉRIFICATION NETLIFY.TOML :"
echo "   ✅ Le fichier netlify.toml est déjà configuré"
echo "   ✅ Proxy N8N configuré vers srv765811.hstgr.cloud"
echo "   ✅ Redirections SPA activées"
echo "   ✅ Headers de sécurité définis"
echo ""

echo "🚀 DÉCLENCHEMENT AUTOMATIQUE :"
echo "   • Push sur 'main' ou 'feature/boutons-suivant-ipad' → Déploiement production"
echo "   • Pull Request → Déploiement preview"
echo "   • Build automatique en ~2-4 minutes"
echo ""

echo "🔍 MONITORING DU DÉPLOIEMENT :"
echo "   • GitHub Actions : Onglet 'Actions' du repository"
echo "   • Netlify Dashboard : Onglet 'Deploys' de votre site"
echo "   • Logs détaillés dans les deux interfaces"
echo ""

echo "⚡ COMMANDES RAPIDES POUR TESTER :"
echo ""
echo "# Test local du build"
echo "npm run build"
echo ""
echo "# Push pour déclencher le déploiement"
echo "git add ."
echo "git commit -m 'trigger: Test déploiement automatique'"
echo "git push"
echo ""

echo "✅ FICHIERS CRÉÉS :"
echo "   📄 .github/workflows/netlify-deploy.yml"
echo "   📄 netlify.toml (existant et configuré)"
echo "   📄 DEPLOYMENT_GUIDE.md"
echo "   📄 deploy-netlify-preparation.sh"
echo ""

echo "🎯 RÉSULTAT ATTENDU :"
echo "   Une fois configuré, chaque push déclenchera automatiquement :"
echo "   • Build TypeScript + Vite"
echo "   • Tests de validation"
echo "   • Déploiement sur Netlify"
echo "   • Mise à jour du site en production"
echo ""

echo "💡 TIPS :"
echo "   • Gardez les tokens secrets précieusement"
echo "   • Testez d'abord avec une branche de développement"
echo "   • Vérifiez les logs en cas d'échec"
echo "   • Le déploiement prend environ 2-4 minutes"
echo ""
echo "🚀 Prêt pour l'automatisation complète !"
