name: CI

on:
  push:
    branches: [ main, develop, chore/ci-setup ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node from .nvmrc
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Type check
        run: npm run typecheck

      - name: Lint (CI mode)
        run: npm run lint:ci

      - name: Format check
        run: npm run format:check

      - name: Build
        run: npm run build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/
          cache: 'npm'

      - name: Install deps (clean)
        run: npm ci

      - name: Show environment
        run: |
          node -v
          npm -v
          npx vite --version || true

      # Qualité (rapports stricts). Ajuste si besoin.
      - name: Lint HTML
        run: npm run lint:html

      - name: Validate HTML
        run: npm run validate:html

      - name: Lint JS/TS
        run: npm run lint:js

      - name: Check formatting
        run: npm run check:format

      - name: Build (Vite)
        run: npm run build

      # Artefacts utiles (dist) quand c'est vert
      - name: Upload build artifact
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist

      # Logs de debug si échec
      - name: Upload npm logs
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: npm-logs
          path: ~/.npm/_logs

  deploy_netlify:
    if: github.ref == 'refs/heads/main'
    needs: [build-test]
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Install deps
        run: npm ci

      - name: Export commit SHA for cache-busting
        run: |
          echo "VITE_COMMIT_SHA=${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Build (prod)
        run: npm run build
        env:
          VITE_COMMIT_SHA: ${{ env.VITE_COMMIT_SHA }}

      - name: Deploy to Netlify (prod)
        run: |
          npm i -g netlify-cli
          netlify deploy \
            --dir=dist \
            --prod \
            --message "CI deploy ${GITHUB_SHA::7}" \
            --site "$NETLIFY_SITE_ID" \
            --auth "$NETLIFY_AUTH_TOKEN"
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}

      - name: Output URLs
        run: |
          echo "✅ Déployé avec commit: ${GITHUB_SHA::7}"
          echo "👉 Ouvre l'app iPad et vérifie le label build."
